title: Michal Grzadkowski
email: mgrzad@gmail.com
description: Michal's work portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: michal-g

# Build settings
markdown: kramdown
remote_theme: eliottvincent/bay
plugins:
  - jekyll-feed

header:
  pages:
    - name: Publications
      slug: pubs
    - name: Gallery

footer:
  show_powered_by: true
  contact:
    - name: Gmail
      value: mgrzad@gmail.com
  follow:
    - name: LinkedIn
      link: http://www.linkedin.com/in/michal-grzadkowski-1b9676201
    - name: GitHub
      link: http://github.com/michal-g

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
