# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Michal Grzadkowski
email: mgrzad@gmail.com
description: >-
	Michal's work portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: michal-g

# Build settings
markdown: kramdown
remote_theme: eliottvincent/bay
plugins:
  - jekyll-feed

header:
  pages:
    - name: Publications
      slug: pubs
    - name: Gallery

footer:
  show_powered_by: true
  contact:
    - name: Gmail
      value: mgrzad@gmail.com
  follow:
    - name: LinkedIn
      link: http://www.linkedin.com/in/michal-grzadkowski-1b9676201
    - name: GitHub
      link: http://github.com/michal-g

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
